//
//  config.h
//  tccproject
//
//  Created by eddy.wu on 11/24/17.
//  Copyright © 2017 eddy.wu. All rights reserved.
//

#ifndef config_h
#define config_h


#endif /* config_h */

/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#define GCC_MAJOR 4
#define GCC_MINOR 2
#define HOST_X86_64 1
#define TCC_VERSION "0.9.26"
